import {
  dag,
  Directory,
  object,
  func,
} from "@dagger.io/dagger";

@object()
export class HyliusPipeline {
  @func()
  async buildAndPush(
    source: Directory,
    registry: string,
    image: string,
    tag: string,
    webhookUrl: string,
    webhookToken: string,
    repo: string,
    sha: string,
    ref: string,
  ): Promise<string> {
    const imageFull = `${image.toLowerCase()}:${tag}`;

    // Build — Dockerfile is always present (generated by Nixpacks in workflow if needed)
    const built = dag.container().build(source);

    // Push to registry
    const digest = await built.publish(imageFull);

    // Notify Hylius dashboard
    await this.notifyHylius({ webhookUrl, webhookToken, image: imageFull, sha, repo, ref });

    return `Published ${imageFull} @ ${digest}`;
  }

  private async notifyHylius(opts: {
    webhookUrl: string;
    webhookToken: string;
    image: string;
    sha: string;
    repo: string;
    ref: string;
  }): Promise<void> {
    const payload = JSON.stringify({
      image: opts.image,
      sha: opts.sha,
      repo: opts.repo,
      ref: opts.ref,
    });

    await dag
      .container()
      .from("curlimages/curl:latest")
      .withExec([
        "curl", "-fsSL",
        "-X", "POST", opts.webhookUrl,
        "-H", "Content-Type: application/json",
        "-H", `Authorization: Bearer ${opts.webhookToken}`,
        "-d", payload,
      ])
      .sync();
  }
}
